- name: install vim
  apt: package={{item}}
  with_items:
  - vim
  - vim-youcompleteme
  tags:
    - vim
- name: install vundle
  file: path=/home/vagrant/.vim/bundle state=directory 
  tags:
    - vim
- git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/vagrant/.vim/bundle/Vundle.vim
  tags:
    - vim
- copy: src=vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant
  tags:
    - vim
- name: clone vim-colorschemes
  git: repo=https://github.com/flazz/vim-colorschemes.git dest=/home/vagrant/.vim/bundle/vim-colorschemes
  tags:
    - vim
- name: copy solarized
  copy: src=/home/vagrant/.vim/bundle/vim-colorschemes/colors/solarized.vim dest=/home/vagrant/.vim/colors
  tags:
    - vim
- command: vim +PluginInstall +qall now
  tags:
    - vim
- command: /home/vagrant/.vim/bundle/YouCompleteMe/install.sh
  args:
    chdir: /home/vagrant/.vim/bundle/YouCompleteMe/
  tags:
    - vim
    - YCM
